//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFareSystem1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInformation", ReplyAction="*")]
        AutoFareSystem1.ServiceReference1.GetStudentInformationResponse GetStudentInformation(AutoFareSystem1.ServiceReference1.GetStudentInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetStudentInformationResponse> GetStudentInformationAsync(AutoFareSystem1.ServiceReference1.GetStudentInformationRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentFares", ReplyAction="*")]
        AutoFareSystem1.ServiceReference1.GetStudentFaresResponse GetStudentFares(AutoFareSystem1.ServiceReference1.GetStudentFaresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentFares", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetStudentFaresResponse> GetStudentFaresAsync(AutoFareSystem1.ServiceReference1.GetStudentFaresRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdministratorInformation", ReplyAction="*")]
        AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponse GetAdministratorInformation(AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdministratorInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponse> GetAdministratorInformationAsync(AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentInformation", Namespace="http://tempuri.org/", Order=0)]
        public AutoFareSystem1.ServiceReference1.GetStudentInformationRequestBody Body;
        
        public GetStudentInformationRequest() {
        }
        
        public GetStudentInformationRequest(AutoFareSystem1.ServiceReference1.GetStudentInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetStudentInformationRequestBody() {
        }
        
        public GetStudentInformationRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoFareSystem1.ServiceReference1.GetStudentInformationResponseBody Body;
        
        public GetStudentInformationResponse() {
        }
        
        public GetStudentInformationResponse(AutoFareSystem1.ServiceReference1.GetStudentInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentInformationResult;
        
        public GetStudentInformationResponseBody() {
        }
        
        public GetStudentInformationResponseBody(string GetStudentInformationResult) {
            this.GetStudentInformationResult = GetStudentInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentFaresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentFares", Namespace="http://tempuri.org/", Order=0)]
        public AutoFareSystem1.ServiceReference1.GetStudentFaresRequestBody Body;
        
        public GetStudentFaresRequest() {
        }
        
        public GetStudentFaresRequest(AutoFareSystem1.ServiceReference1.GetStudentFaresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentFaresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetStudentFaresRequestBody() {
        }
        
        public GetStudentFaresRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentFaresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentFaresResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoFareSystem1.ServiceReference1.GetStudentFaresResponseBody Body;
        
        public GetStudentFaresResponse() {
        }
        
        public GetStudentFaresResponse(AutoFareSystem1.ServiceReference1.GetStudentFaresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentFaresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentFaresResult;
        
        public GetStudentFaresResponseBody() {
        }
        
        public GetStudentFaresResponseBody(string GetStudentFaresResult) {
            this.GetStudentFaresResult = GetStudentFaresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdministratorInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdministratorInformation", Namespace="http://tempuri.org/", Order=0)]
        public AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequestBody Body;
        
        public GetAdministratorInformationRequest() {
        }
        
        public GetAdministratorInformationRequest(AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAdministratorInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetAdministratorInformationRequestBody() {
        }
        
        public GetAdministratorInformationRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdministratorInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdministratorInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponseBody Body;
        
        public GetAdministratorInformationResponse() {
        }
        
        public GetAdministratorInformationResponse(AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAdministratorInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAdministratorInformationResult;
        
        public GetAdministratorInformationResponseBody() {
        }
        
        public GetAdministratorInformationResponseBody(string GetAdministratorInformationResult) {
            this.GetAdministratorInformationResult = GetAdministratorInformationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : AutoFareSystem1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<AutoFareSystem1.ServiceReference1.WebService1Soap>, AutoFareSystem1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoFareSystem1.ServiceReference1.GetStudentInformationResponse AutoFareSystem1.ServiceReference1.WebService1Soap.GetStudentInformation(AutoFareSystem1.ServiceReference1.GetStudentInformationRequest request) {
            return base.Channel.GetStudentInformation(request);
        }
        
        public string GetStudentInformation(string id) {
            AutoFareSystem1.ServiceReference1.GetStudentInformationRequest inValue = new AutoFareSystem1.ServiceReference1.GetStudentInformationRequest();
            inValue.Body = new AutoFareSystem1.ServiceReference1.GetStudentInformationRequestBody();
            inValue.Body.id = id;
            AutoFareSystem1.ServiceReference1.GetStudentInformationResponse retVal = ((AutoFareSystem1.ServiceReference1.WebService1Soap)(this)).GetStudentInformation(inValue);
            return retVal.Body.GetStudentInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetStudentInformationResponse> AutoFareSystem1.ServiceReference1.WebService1Soap.GetStudentInformationAsync(AutoFareSystem1.ServiceReference1.GetStudentInformationRequest request) {
            return base.Channel.GetStudentInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetStudentInformationResponse> GetStudentInformationAsync(string id) {
            AutoFareSystem1.ServiceReference1.GetStudentInformationRequest inValue = new AutoFareSystem1.ServiceReference1.GetStudentInformationRequest();
            inValue.Body = new AutoFareSystem1.ServiceReference1.GetStudentInformationRequestBody();
            inValue.Body.id = id;
            return ((AutoFareSystem1.ServiceReference1.WebService1Soap)(this)).GetStudentInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoFareSystem1.ServiceReference1.GetStudentFaresResponse AutoFareSystem1.ServiceReference1.WebService1Soap.GetStudentFares(AutoFareSystem1.ServiceReference1.GetStudentFaresRequest request) {
            return base.Channel.GetStudentFares(request);
        }
        
        public string GetStudentFares(string id) {
            AutoFareSystem1.ServiceReference1.GetStudentFaresRequest inValue = new AutoFareSystem1.ServiceReference1.GetStudentFaresRequest();
            inValue.Body = new AutoFareSystem1.ServiceReference1.GetStudentFaresRequestBody();
            inValue.Body.id = id;
            AutoFareSystem1.ServiceReference1.GetStudentFaresResponse retVal = ((AutoFareSystem1.ServiceReference1.WebService1Soap)(this)).GetStudentFares(inValue);
            return retVal.Body.GetStudentFaresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetStudentFaresResponse> AutoFareSystem1.ServiceReference1.WebService1Soap.GetStudentFaresAsync(AutoFareSystem1.ServiceReference1.GetStudentFaresRequest request) {
            return base.Channel.GetStudentFaresAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetStudentFaresResponse> GetStudentFaresAsync(string id) {
            AutoFareSystem1.ServiceReference1.GetStudentFaresRequest inValue = new AutoFareSystem1.ServiceReference1.GetStudentFaresRequest();
            inValue.Body = new AutoFareSystem1.ServiceReference1.GetStudentFaresRequestBody();
            inValue.Body.id = id;
            return ((AutoFareSystem1.ServiceReference1.WebService1Soap)(this)).GetStudentFaresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponse AutoFareSystem1.ServiceReference1.WebService1Soap.GetAdministratorInformation(AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest request) {
            return base.Channel.GetAdministratorInformation(request);
        }
        
        public string GetAdministratorInformation(string id) {
            AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest inValue = new AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest();
            inValue.Body = new AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequestBody();
            inValue.Body.id = id;
            AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponse retVal = ((AutoFareSystem1.ServiceReference1.WebService1Soap)(this)).GetAdministratorInformation(inValue);
            return retVal.Body.GetAdministratorInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponse> AutoFareSystem1.ServiceReference1.WebService1Soap.GetAdministratorInformationAsync(AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest request) {
            return base.Channel.GetAdministratorInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoFareSystem1.ServiceReference1.GetAdministratorInformationResponse> GetAdministratorInformationAsync(string id) {
            AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest inValue = new AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequest();
            inValue.Body = new AutoFareSystem1.ServiceReference1.GetAdministratorInformationRequestBody();
            inValue.Body.id = id;
            return ((AutoFareSystem1.ServiceReference1.WebService1Soap)(this)).GetAdministratorInformationAsync(inValue);
        }
    }
}
